# Generated by Selenium IDE
import pytest
import time
import json
from base.tests import BaseTestCase
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from django.contrib.staticfiles.testing import StaticLiveServerTestCase


class TestTestiniciosinlogear(StaticLiveServerTestCase):
  def setup_method(self):
    self.base = BaseTestCase()
    self.driver = webdriver.Chrome()
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_testiniciosinlogear(self):
    self.driver.get("http://localhost:8000/booth/inicio/")
    self.driver.set_window_size(1848, 1016)
    self.driver.find_element(By.ID, "alertButton").click()