# Generated by Django 2.0 on 2021-12-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='poll',
            field=models.BooleanField(default=None),
        ),
    ]
