# Generated by Django 2.0 on 2021-12-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20211228_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='poll',
            field=models.BooleanField(default=None, verbose_name='Quick poll'),
        ),
    ]
