# Generated by Django 2.0 on 2021-12-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_types',
            field=models.PositiveIntegerField(choices=[(1, 'Unique option'), (2, 'Rank order')], default='1'),
        ),
    ]
