# Generated by Django 2.0 on 2021-12-20 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('preference', models.CharField(blank=True, choices=[('B', '1'), ('M', '2'), ('A', '3')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='voting',
            name='order_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='voting.OrderQuestion'),
        ),
    ]
