# Generated by Django 2.0 on 2021-12-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20211220_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_types',
            field=models.PositiveIntegerField(choices=[(1, 'Unique option'), (2, 'Multiple option'), (3, 'Rank order scale')], default='1'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='rank_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=models.TextField(unique=True),
        ),
    ]
