# Generated by Django 2.0 on 2022-01-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_question_option_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=models.TextField(unique=True),
        ),
    ]
