# Generated by Django 2.0 on 2021-12-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_voting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
