# Generated by Django 2.0 on 2022-01-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20220103_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=models.TextField(),
        ),
    ]
