# Generated by Django 2.0 on 2021-12-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20211228_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='poll',
            field=models.BooleanField(default=False, verbose_name='Quick poll'),
        ),
    ]
