# Generated by Django 2.0 on 2022-01-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20220103_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'IDENTITY'), (1, 'BORDA')], default='0'),
        ),
    ]
