# Generated by Selenium IDE

from selenium import webdriver
from base.tests import BaseTestCase
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from django.conf import settings

class TestCheck():
  def setUp(self):
    options = webdriver.ChromeOptions()
    options.headless = False
    self.base = BaseTestCase()
    self.base.setUp()
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}


  def tearDown(self):
    self.driver.quit()

  def test_check(self):
    url = settings.BASEURL
    self.driver.get(str(url)+"/admin/login/?next=/admin/")
    self.driver.set_window_size(909, 1016)
    self.driver.find_element(By.ID, "id_username").send_keys("veleta")
    self.driver.find_element(By.ID, "id_password").send_keys("veleta2021")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".model-question .addlink").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > label").click()
    self.driver.find_element(By.ID, "id_question_desc").click()
    self.driver.find_element(By.ID, "id_question_desc").send_keys("Pregunta dicotómica A favor y en contra")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(6)").click()
    self.driver.find_element(By.LINK_TEXT, "Pregunta dicotómica A favor y en contra").click()
    assert self.driver.find_element(By.ID, "id_options-0-option").text == "A favor"
    assert self.driver.find_element(By.ID, "id_options-1-option").text == "En contra"
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.CSS_SELECTOR, ".model-question .addlink").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
    self.driver.find_element(By.ID, "id_question_desc").click()
    self.driver.find_element(By.ID, "id_question_desc").send_keys("Comprobación preguntas SI y NO")
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(6)").click()
    self.driver.find_element(By.LINK_TEXT, "Comprobación preguntas SI y NO").click()
    assert self.driver.find_element(By.ID, "id_options-0-option").text == "SI"
    assert self.driver.find_element(By.ID, "id_options-1-option").text == "NO"

