# Generated by Django 2.0 on 2022-01-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='a',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='b',
            field=models.TextField(),
        ),
    ]
