# Generated by Django 2.0 on 2021-12-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180921_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='a',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='b',
            field=models.TextField(),
        ),
    ]
